trigger: none
pr: none

schedules:
  - cron: '0 7 * * 1-5'
    displayName: Weekday cross-service regression
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.25.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipAzureAuth: true
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    validationJobs:
      - name: Run Cross-service E2E
        steps:
          - template: .azure/pipelines/steps/run-local-e2e.yml@self
            parameters:
              target: cross-service
