trigger: none
pr: none

schedules:
  - cron: '0 6 * * 1-5'
    displayName: Weekday Test smoke
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.30.0

pool: pins-odt-agent-pool

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 1
    skipAzureAuth: true
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
      - template: .azure/pipelines/variables/test-smoke.yml@self
      - template: /variables/environments/test.yml@templates
      - group: pipeline_secrets
    validationJobs:
      - name: Run Manage smoke against Test
        steps:
          - template: .azure/pipelines/steps/run-environment-smoke.yml@self
            parameters:
              displayName: Run Manage smoke against Test
              target: manage
              artifactName: cypress-manage-test-smoke-reports

      - name: Run Portal smoke against Test
        steps:
          - template: .azure/pipelines/steps/run-environment-smoke.yml@self
            parameters:
              displayName: Run Portal smoke against Test
              target: portal
              artifactName: cypress-portal-test-smoke-reports
