BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Authority] (
    [id] UNIQUEIDENTIFIER NOT NULL,
    [name] NVARCHAR(200) NOT NULL,
    [pinsCode] NVARCHAR(20) NOT NULL,
    [status] NVARCHAR(20) NOT NULL,
    CONSTRAINT [Authority_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
