BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Case] ALTER COLUMN [anotherContact] NVARCHAR(10) NOT NULL;
ALTER TABLE [dbo].[Case] ALTER COLUMN [secondaryLPA] NVARCHAR(10) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
