parameters:
  - name: target
    type: string
    values:
      - manage
      - portal
  - name: displayName
    type: string
  - name: artifactName
    type: string
  - name: authenticateAzure
    type: boolean
    default: true
  - name: buildCommit
    type: string
    default: ''

steps:
  - ${{ if ne(parameters.buildCommit, '') }}:
      - checkout: self
        displayName: Clone repo
        persistCredentials: true
        fetchDepth: 0
        fetchTags: false

      - bash: git checkout "${{ parameters.buildCommit }}"
        displayName: Checkout Build-Commit

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)" | package-lock.json
      path: $(npm_config_cache)
    displayName: Cache NPM

  - template: /steps/node_script.yml@templates
    parameters:
      nodeVersion: 24
      script: npm ci
      environmentVariables:
        npm_config_cache: $(npm_config_cache)

  - template: /steps/node_script.yml@templates
    parameters:
      nodeVersion: 24
      script: npm run db-generate

  - ${{ if eq(parameters.authenticateAzure, true) }}:
      - template: /steps/azure_auth.yml@templates

  - template: /steps/azure_get_secrets.yml@templates
    parameters:
      keyVaultName: pins-kv-local-plans-test
      secrets:
        - name: local-plans-sql-app-connection-string
          variable: SQL_CONNECTION_STRING
        - name: localplans-gov-notify-api-key
          variable: GOV_NOTIFY_API_KEY

  - template: /steps/node_script.yml@templates
    parameters:
      nodeVersion: 24
      script: npm run cy:${{ parameters.target }}:test-smoke
      environmentVariables:
        CYPRESS_AUTH_PASSWORD: $(E2E_AUTH_PASSWORD)
        CYPRESS_AUTH_USERNAME: $(e2eAuthUsername)
        GOV_NOTIFY_API_KEY: $(GOV_NOTIFY_API_KEY)
        SQL_CONNECTION_STRING: $(SQL_CONNECTION_STRING)
        ${{ if eq(parameters.target, 'manage') }}:
          CYPRESS_AUTH_USER_ID: $(e2eAuthUserId)
          CYPRESS_NOTIFY_SMOKE_EMAIL: $(e2eAuthUsername)
          MANAGE_BASE_URL: $(manageSmokeBaseUrl)
        ${{ if eq(parameters.target, 'portal') }}:
          CYPRESS_PORTAL_SMOKE_OTP: $(e2ePortalSmokeOtp)
          PORTAL_BASE_URL: $(portalSmokeBaseUrl)

  - bash: mkdir -p cypress/reports
    condition: failed()
    displayName: Prepare ${{ parameters.displayName }} artifacts

  - task: PublishPipelineArtifact@1
    condition: failed()
    displayName: Publish ${{ parameters.displayName }} artifacts
    inputs:
      targetPath: $(Build.Repository.LocalPath)/cypress/reports
      artifact: ${{ parameters.artifactName }}
