BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Document] DROP CONSTRAINT [Document_isTemp_df];
ALTER TABLE [dbo].[Document] ADD CONSTRAINT [Document_isTemp_df] DEFAULT 0 FOR [isTemp];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
