trigger: none

pr: none

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: 488296e47e84b72f515ae0d1c1d63a6c4f37bdae

extends:
  template: pipelines/terraform_plan_apply.yml@templates
  parameters:
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    serviceConnectionPrefix: Azure DevOps Pipelines - Local Plans Examinations - Infrastructure
    storageAccountName: pinssttfstatelocalplans
    resourceGroupName: pins-rg-shared-terraform-uks
    containerPrefix: terraform-state-local-plans-
    workingDirectory: $(Build.Repository.LocalPath)/infrastructure
    environmentVarFilePath: $(Build.Repository.LocalPath)/infrastructure/environments
