BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Gateway3Info] ADD [decision] NVARCHAR(1000);

-- AlterTable
ALTER TABLE [dbo].[LPA] DROP CONSTRAINT [LPA_lpaName_default];
ALTER TABLE [dbo].[LPA] ADD CONSTRAINT [LPA_lpaName_df] DEFAULT '' FOR [lpaName];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
